expname: None
rand: 3

data:

  near: 0.0
  far: 6.0

model:
  net_w: 128
  N_samples: 128
  framework: GaussNeRF
  
  # nerf-minus-minus
  so3_representation: 'axis-angle'


training:
  # learning rate anneal
  step_size_nerf: 200       # unit: epochs
  lr_anneal_nerf: 0.9954   # 0.9954
  lr_nerf: 1.0e-3

  step_size_param: 2000     # unit: epochs
  lr_anneal_param: 0.9000
  lr_param: 1.0e-3

  novel_view_synthesis: false  # whether do novel view synthesis during traning